import React, { useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle2, ChevronDown, Clock3, Eye, MoreHorizontal, Play, RefreshCw, Search, X } from 'lucide-react';

type TaskStatus = 'running' | 'completed' | 'failed';
type DifferenceStatus = 'pending' | 'processing' | 'resolved' | 'ignored';
type DifferenceSeverity = 'high' | 'medium' | 'low';
type InspectionTask = { id: string; name: string; channel: string; stores: string; status: TaskStatus; progress: number; differenceCount: number; failedCount: number; createdAt: string; finishedAt?: string };
type DifferenceRecord = { id: string; productName: string; productId: string; channel: string; storeRange: string; fieldGroup: string; fieldName: string; masterValue: string; platformValue: string; severity: DifferenceSeverity; status: DifferenceStatus; detectedAt: string };

const TASKS: InspectionTask[] = [
  { id: 'DI202608010026', name: '美团全量商品日常巡检', channel: '美团外卖', stores: '128 家门店', status: 'completed', progress: 100, differenceCount: 23, failedCount: 0, createdAt: '08-01 09:00', finishedAt: '08-01 09:18' },
  { id: 'DI202608010025', name: '饿了么价格专项巡检', channel: '饿了么', stores: '86 家门店', status: 'running', progress: 68, differenceCount: 11, failedCount: 2, createdAt: '08-01 08:42' },
  { id: 'DI202607310019', name: '抖音结构与图片巡检', channel: '抖音团购', stores: '42 家门店', status: 'failed', progress: 37, differenceCount: 7, failedCount: 16, createdAt: '07-31 22:00', finishedAt: '07-31 22:12' },
];
const DIFFERENCES: DifferenceRecord[] = [
  { id: 'DF-1026', productName: '金桔柠檬茶', productId: 'SP00012876', channel: '美团外卖', storeRange: '南山万象店等 18 家', fieldGroup: '基础信息', fieldName: '商品名称', masterValue: '金桔柠檬茶', platformValue: '金桔柠檬饮', severity: 'high', status: 'pending', detectedAt: '08-01 09:12' },
  { id: 'DF-1027', productName: '双拼鸡腿饭', productId: 'SP00012877', channel: '美团外卖', storeRange: '42 家门店', fieldGroup: '图片', fieldName: '主图', masterValue: '企迈主图 800×800', platformValue: '平台图片 640×480', severity: 'high', status: 'processing', detectedAt: '08-01 09:13' },
  { id: 'DF-1028', productName: '超值午餐套餐', productId: 'SP00012878', channel: '饿了么', storeRange: '86 家门店', fieldGroup: '价格', fieldName: '销售价', masterValue: '¥39.00', platformValue: '¥42.00', severity: 'medium', status: 'pending', detectedAt: '08-01 09:15' },
  { id: 'DF-1029', productName: '港式奶茶', productId: 'SP00012879', channel: '美团外卖', storeRange: '福田卓悦店', fieldGroup: '分类', fieldName: '平台分类', masterValue: '现制饮品 / 奶茶', platformValue: '饮品 / 其他', severity: 'low', status: 'ignored', detectedAt: '08-01 09:16' },
];
const STATUS_LABELS: Record<TaskStatus, string> = { running: '巡检中', completed: '已完成', failed: '部分失败' };
const DIFF_STATUS_LABELS: Record<DifferenceStatus, string> = { pending: '待处理', processing: '处理中', resolved: '已解决', ignored: '已忽略' };
const SEVERITY_LABELS: Record<DifferenceSeverity, string> = { high: '高', medium: '中', low: '低' };

export const WebDifferenceInspection: React.FC = () => {
  const [tab, setTab] = useState<'tasks' | 'differences'>('tasks');
  const [tasks, setTasks] = useState(TASKS);
  const [differences, setDifferences] = useState(DIFFERENCES);
  const [keyword, setKeyword] = useState('');
  const [status, setStatus] = useState('all');
  const [channel, setChannel] = useState('all');
  const [selectedIds, setSelectedIds] = useState<string[]>([]);
  const [taskDetail, setTaskDetail] = useState<InspectionTask | null>(null);
  const [differenceDetail, setDifferenceDetail] = useState<DifferenceRecord | null>(null);
  const [createOpen, setCreateOpen] = useState(false);
  const [pendingAction, setPendingAction] = useState<{ action: 'overwrite' | 'accept' | 'ignore'; records: DifferenceRecord[] } | null>(null);
  const [toast, setToast] = useState('');
  const feedback = (text: string) => { setToast(text); window.setTimeout(() => setToast(''), 2600); };
  const filteredTasks = useMemo(() => tasks.filter(item => (!keyword.trim() || `${item.name} ${item.id} ${item.channel} ${item.stores}`.toLowerCase().includes(keyword.trim().toLowerCase())) && (status === 'all' || item.status === status) && (channel === 'all' || item.channel === channel)), [channel, keyword, status, tasks]);
  const filteredDifferences = useMemo(() => differences.filter(item => (!keyword.trim() || `${item.productName} ${item.productId} ${item.fieldName} ${item.channel}`.toLowerCase().includes(keyword.trim().toLowerCase())) && (status === 'all' || item.status === status) && (channel === 'all' || item.channel === channel)), [channel, differences, keyword, status]);
  const reset = () => { setKeyword(''); setStatus('all'); setChannel('all'); setSelectedIds([]); };
  const executeAction = () => { if (!pendingAction) return; const ids = pendingAction.records.map(item => item.id); setDifferences(current => current.map(item => ids.includes(item.id) ? { ...item, status: pendingAction.action === 'ignore' ? 'ignored' : pendingAction.action === 'accept' ? 'resolved' : 'processing' } : item)); feedback(pendingAction.action === 'overwrite' ? `已创建覆盖平台发布任务，涉及 ${ids.length} 条差异` : pendingAction.action === 'accept' ? `已接受 ${ids.length} 条平台值并生成主档变更记录` : `已忽略 ${ids.length} 条差异`); setPendingAction(null); setSelectedIds([]); setDifferenceDetail(null); };

  return <div className="relative flex min-h-0 min-w-0 flex-1 overflow-hidden bg-[#F5F6FA] p-3">
    {toast && <div className="absolute left-1/2 top-4 z-[100] -translate-x-1/2 rounded-md bg-[#1D2129] px-4 py-2 text-[13px] text-white shadow-lg">{toast}</div>}
    <div className="console-panel flex min-h-0 min-w-0 flex-1 flex-col overflow-hidden">
      <div className="flex h-12 shrink-0 items-end justify-between border-b border-[#E5E7EB] px-4"><div className="flex h-full items-end gap-6">{(['tasks', 'differences'] as const).map(key => <button key={key} onClick={() => { setTab(key); reset(); }} className={`h-full border-b-2 px-1 text-[13px] font-medium ${tab === key ? 'border-[#00B460] text-[#008F4C]' : 'border-transparent text-[#667085]'}`}>{key === 'tasks' ? `巡检任务（${tasks.length}）` : `差异处置（${differences.filter(item => item.status === 'pending').length}）`}</button>)}</div><button onClick={() => setCreateOpen(true)} className="mb-1.5 inline-flex h-9 items-center rounded-md bg-[#00B460] px-4 text-[13px] font-medium text-white"><Play size={15} className="mr-1.5" />发起巡检</button></div>
      <div className="flex shrink-0 items-center justify-between gap-3 border-b border-[#E9EDF2] px-4 py-3"><div className="flex items-center gap-2"><label className="relative"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-[#98A2B3]" /><input value={keyword} onChange={e => setKeyword(e.target.value)} placeholder={tab === 'tasks' ? '任务名称、任务ID、渠道或门店' : '商品名称、商品ID、字段或渠道'} className="h-9 w-[310px] rounded-md border border-[#DDE2E8] pl-9 pr-3 text-[13px] outline-none focus:border-[#00B460]" /></label><Select value={channel} onChange={setChannel} label="渠道" options={['美团外卖', '饿了么', '抖音团购']} /><Select value={status} onChange={setStatus} label="状态" options={tab === 'tasks' ? ['running', 'completed', 'failed'] : ['pending', 'processing', 'resolved', 'ignored']} optionLabels={tab === 'tasks' ? STATUS_LABELS : DIFF_STATUS_LABELS} /><button onClick={reset} className="h-9 rounded-md border border-[#DDE2E8] px-4 text-[13px]">重置</button></div>{tab === 'differences' && <div className="flex items-center gap-2"><button disabled={!selectedIds.length} onClick={() => setPendingAction({ action: 'ignore', records: differences.filter(item => selectedIds.includes(item.id)) })} className="h-9 rounded-md border border-[#DDE2E8] px-3 text-[13px] disabled:opacity-40">批量忽略</button><button disabled={!selectedIds.length} onClick={() => setPendingAction({ action: 'overwrite', records: differences.filter(item => selectedIds.includes(item.id)) })} className="h-9 rounded-md border border-[#00B460] px-3 text-[13px] text-[#008F4C] disabled:opacity-40">批量覆盖平台</button></div>}</div>
      <div className="flex shrink-0 items-center justify-between border-b border-[#E9EDF2] px-4 py-2.5 text-[13px] text-[#667085]">{tab === 'tasks' ? <><span>共 <strong className="text-[#1D2129]">{filteredTasks.length}</strong> 个任务 · 运行中 {tasks.filter(item => item.status === 'running').length} · 部分失败 {tasks.filter(item => item.status === 'failed').length}</span><span>巡检只读取平台现状，不直接修改企迈或平台数据</span></> : <><span>共 <strong className="text-[#1D2129]">{filteredDifferences.length}</strong> 条差异 · 高风险 {differences.filter(item => item.severity === 'high' && item.status === 'pending').length}</span><span>覆盖平台将创建发布任务；接受平台值将生成主档变更记录</span></>}</div>
      <div className="min-h-0 flex-1 overflow-auto">{tab === 'tasks' ? <TaskTable tasks={filteredTasks} onDetail={setTaskDetail} onRetry={task => { setTasks(current => current.map(item => item.id === task.id ? { ...item, status: 'running', progress: Math.max(item.progress, 38), failedCount: 0 } : item)); feedback(`任务“${task.name}”已从失败位置重试`); }} /> : <DifferenceTable records={filteredDifferences} selectedIds={selectedIds} onSelectedIdsChange={setSelectedIds} onDetail={setDifferenceDetail} />}{(tab === 'tasks' ? filteredTasks.length : filteredDifferences.length) === 0 && <div className="flex h-56 flex-col items-center justify-center text-[13px] text-[#98A2B3]"><Search size={28} className="mb-3" /><span>没有符合当前条件的{tab === 'tasks' ? '巡检任务' : '差异'}</span><button onClick={reset} className="mt-2 text-[#008F4C]">清空筛选</button></div>}</div>
    </div>
    {taskDetail && <TaskDrawer task={taskDetail} onClose={() => setTaskDetail(null)} onOpenDifferences={() => { setTaskDetail(null); setTab('differences'); reset(); }} />}
    {differenceDetail && <DifferenceDrawer record={differenceDetail} onClose={() => setDifferenceDetail(null)} onAction={action => setPendingAction({ action, records: [differenceDetail] })} />}
    {createOpen && <CreateInspectionModal onClose={() => setCreateOpen(false)} onCreate={(task) => { setTasks(current => [task, ...current]); setCreateOpen(false); feedback('巡检任务已创建，正在读取平台商品数据'); }} />}
    {pendingAction && <ConfirmAction state={pendingAction} onClose={() => setPendingAction(null)} onConfirm={executeAction} />}
  </div>;
};

const TaskTable = ({ tasks, onDetail, onRetry }: { tasks: InspectionTask[]; onDetail: (task: InspectionTask) => void; onRetry: (task: InspectionTask) => void }) => <table className="w-full min-w-[1080px] table-fixed border-collapse text-left text-[13px]"><thead className="sticky top-0 z-10 bg-[#F7F8FA] text-[#4E5969]"><tr className="border-b border-[#E5E7EB]"><th className="w-[260px] px-4 py-3 font-medium">任务名称 / ID</th><th className="w-[150px] px-3 py-3 font-medium">渠道</th><th className="w-[180px] px-3 py-3 font-medium">门店范围</th><th className="w-[210px] px-3 py-3 font-medium">进度</th><th className="w-[150px] px-3 py-3 font-medium">差异 / 失败</th><th className="px-3 py-3 font-medium">时间</th><th className="w-[150px] px-3 py-3 font-medium">操作</th></tr></thead><tbody>{tasks.map(task => <tr key={task.id} className="border-b border-[#EEF0F3] hover:bg-[#FAFCFB]"><td className="px-4 py-3"><button onClick={() => onDetail(task)} className="font-medium text-[#1D2129] hover:text-[#008F4C]">{task.name}</button><div className="mt-1 text-[12px] text-[#98A2B3]">{task.id}</div></td><td className="px-3 py-3">{task.channel}</td><td className="px-3 py-3">{task.stores}</td><td className="px-3 py-3"><div className="flex items-center gap-2"><div className="h-1.5 flex-1 rounded-full bg-[#EEF0F3]"><div className={`h-full rounded-full ${task.status === 'failed' ? 'bg-[#F04438]' : 'bg-[#00B460]'}`} style={{ width: `${task.progress}%` }} /></div><span className="w-9 text-right">{task.progress}%</span></div><div className="mt-1 text-[12px] text-[#667085]">{STATUS_LABELS[task.status]}</div></td><td className="px-3 py-3"><span className="text-[#B42318]">{task.differenceCount} 条差异</span><span className="ml-2 text-[#667085]">{task.failedCount} 失败</span></td><td className="px-3 py-3 text-[#667085]">创建 {task.createdAt}<br />{task.finishedAt ? `完成 ${task.finishedAt}` : '尚未完成'}</td><td className="px-3 py-3"><div className="flex gap-3"><button onClick={() => onDetail(task)} className="text-[#008F4C]">查看</button>{task.status === 'failed' && <button onClick={() => onRetry(task)} className="inline-flex items-center text-[#008F4C]"><RefreshCw size={13} className="mr-1" />重试</button>}<button type="button" disabled title="当前任务没有更多可用操作" className="cursor-not-allowed opacity-40"><MoreHorizontal size={17} className="text-[#667085]" /></button></div></td></tr>)}</tbody></table>;

const DifferenceTable = ({ records, selectedIds, onSelectedIdsChange, onDetail }: { records: DifferenceRecord[]; selectedIds: string[]; onSelectedIdsChange: (ids: string[]) => void; onDetail: (record: DifferenceRecord) => void }) => { const all = records.length > 0 && records.every(item => selectedIds.includes(item.id)); return <table className="w-full min-w-[1180px] table-fixed border-collapse text-left text-[13px]"><thead className="sticky top-0 z-10 bg-[#F7F8FA] text-[#4E5969]"><tr className="border-b border-[#E5E7EB]"><th className="w-10 px-4 py-3"><input type="checkbox" checked={all} onChange={() => onSelectedIdsChange(all ? selectedIds.filter(id => !records.some(item => item.id === id)) : Array.from(new Set([...selectedIds, ...records.map(item => item.id)])))} /></th><th className="w-[210px] px-3 py-3 font-medium">商品</th><th className="w-[180px] px-3 py-3 font-medium">渠道 / 门店</th><th className="w-[150px] px-3 py-3 font-medium">差异字段</th><th className="px-3 py-3 font-medium">企迈值 / 平台值</th><th className="w-[100px] px-3 py-3 font-medium">风险</th><th className="w-[110px] px-3 py-3 font-medium">状态</th><th className="w-[110px] px-3 py-3 font-medium">操作</th></tr></thead><tbody>{records.map(record => <tr key={record.id} className="border-b border-[#EEF0F3] hover:bg-[#FAFCFB]"><td className="px-4 py-3"><input type="checkbox" checked={selectedIds.includes(record.id)} onChange={() => onSelectedIdsChange(selectedIds.includes(record.id) ? selectedIds.filter(id => id !== record.id) : [...selectedIds, record.id])} /></td><td className="px-3 py-3"><button onClick={() => onDetail(record)} className="font-medium text-[#1D2129] hover:text-[#008F4C]">{record.productName}</button><div className="mt-1 text-[12px] text-[#98A2B3]">{record.productId} · {record.id}</div></td><td className="px-3 py-3"><div>{record.channel}</div><div className="mt-1 text-[12px] text-[#667085]">{record.storeRange}</div></td><td className="px-3 py-3"><div>{record.fieldName}</div><div className="mt-1 text-[12px] text-[#98A2B3]">{record.fieldGroup}</div></td><td className="px-3 py-3"><div className="truncate"><span className="text-[#98A2B3]">企迈：</span>{record.masterValue}</div><div className="mt-1 truncate"><span className="text-[#98A2B3]">平台：</span>{record.platformValue}</div></td><td className="px-3 py-3"><span className={`rounded px-2 py-1 text-[12px] ${record.severity === 'high' ? 'bg-[#FFF1F0] text-[#B42318]' : record.severity === 'medium' ? 'bg-[#FFF7E8] text-[#B54708]' : 'bg-[#F2F4F7] text-[#667085]'}`}>{SEVERITY_LABELS[record.severity]}</span></td><td className="px-3 py-3">{DIFF_STATUS_LABELS[record.status]}</td><td className="px-3 py-3"><button onClick={() => onDetail(record)} className="inline-flex items-center text-[#008F4C]"><Eye size={14} className="mr-1" />对照处置</button></td></tr>)}</tbody></table>; };

const TaskDrawer = ({ task, onClose, onOpenDifferences }: { task: InspectionTask; onClose: () => void; onOpenDifferences: () => void }) => <div className="fixed inset-0 z-[80] flex justify-end bg-black/35"><div className="flex h-full w-[560px] flex-col bg-white shadow-2xl"><DrawerHeader title="巡检任务详情" onClose={onClose} /><div className="flex-1 space-y-5 overflow-y-auto p-5 text-[13px]"><div className="rounded-md bg-[#F7F8FA] p-4"><div className="font-medium">{task.name}</div><div className="mt-1 text-[#667085]">{task.id} · {STATUS_LABELS[task.status]}</div></div><Field label="巡检范围" value={`${task.channel} · ${task.stores}`} /><Field label="执行进度" value={`${task.progress}% · 发现 ${task.differenceCount} 条差异 · ${task.failedCount} 个对象失败`} /><Field label="执行时间" value={`创建 ${task.createdAt}${task.finishedAt ? ` · 完成 ${task.finishedAt}` : ''}`} /><div><div className="mb-2 text-[12px] text-[#98A2B3]">处理记录</div><div className="space-y-3 border-l border-[#DDE2E8] pl-4"><p><Clock3 size={13} className="mr-1 inline" />创建任务并冻结巡检范围</p><p>读取平台商品与企迈发布快照</p><p>{task.status === 'running' ? '正在计算字段差异' : '已生成差异处置清单'}</p></div></div></div><div className="flex justify-end gap-2 border-t border-[#E5E7EB] px-5 py-3"><button onClick={onClose} className="h-9 rounded-md border border-[#DDE2E8] px-4 text-[13px]">关闭</button><button onClick={onOpenDifferences} className="h-9 rounded-md bg-[#00B460] px-4 text-[13px] font-medium text-white">查看差异</button></div></div></div>;

const DifferenceDrawer = ({ record, onClose, onAction }: { record: DifferenceRecord; onClose: () => void; onAction: (action: 'overwrite' | 'accept' | 'ignore') => void }) => <div className="fixed inset-0 z-[80] flex justify-end bg-black/35"><div className="flex h-full w-[680px] flex-col bg-white shadow-2xl"><DrawerHeader title="差异对照与处置" onClose={onClose} /><div className="flex-1 space-y-5 overflow-y-auto p-5 text-[13px]"><div className="rounded-md bg-[#F7F8FA] p-4"><div className="font-medium">{record.productName}</div><div className="mt-1 text-[#667085]">{record.productId} · {record.channel} · {record.storeRange}</div></div><div className="grid grid-cols-2 overflow-hidden rounded-md border border-[#E5E7EB]"><div className="border-r border-[#E5E7EB]"><div className="bg-[#F7F8FA] px-4 py-2.5 font-medium">企迈发布快照</div><div className="p-4"><div className="text-[12px] text-[#98A2B3]">{record.fieldGroup} / {record.fieldName}</div><div className="mt-2 text-[15px] font-medium">{record.masterValue}</div></div></div><div><div className="bg-[#FFF8F0] px-4 py-2.5 font-medium text-[#B54708]">平台当前值</div><div className="p-4"><div className="text-[12px] text-[#98A2B3]">{record.fieldGroup} / {record.fieldName}</div><div className="mt-2 text-[15px] font-medium">{record.platformValue}</div></div></div></div><Field label="发现时间与状态" value={`${record.detectedAt} · ${SEVERITY_LABELS[record.severity]}风险 · ${DIFF_STATUS_LABELS[record.status]}`} /><div className="rounded-md border border-[#FECACA] bg-[#FFF7F6] p-3 leading-6 text-[#B42318]">覆盖平台会创建发布任务，不会在本页直接调用平台；接受平台值会生成可审计的主档变更记录；忽略只关闭本次差异。</div></div><div className="flex items-center justify-between border-t border-[#E5E7EB] px-5 py-3"><button onClick={() => onAction('ignore')} className="h-9 rounded-md border border-[#DDE2E8] px-4 text-[13px]">忽略本次</button><div className="flex gap-2"><button onClick={() => onAction('accept')} className="h-9 rounded-md border border-[#00B460] px-4 text-[13px] text-[#008F4C]">接受平台值</button><button onClick={() => onAction('overwrite')} className="h-9 rounded-md bg-[#00B460] px-4 text-[13px] font-medium text-white">覆盖平台</button></div></div></div></div>;

const CreateInspectionModal = ({ onClose, onCreate }: { onClose: () => void; onCreate: (task: InspectionTask) => void }) => { const [name, setName] = useState(''); const [channel, setChannel] = useState('美团外卖'); const [stores, setStores] = useState('全部已绑定门店'); const [scope, setScope] = useState('全部字段'); const [error, setError] = useState(''); const submit = () => { if (!name.trim()) return setError('请输入巡检任务名称'); onCreate({ id: `DI${Date.now()}`, name: name.trim(), channel, stores, status: 'running', progress: 0, differenceCount: 0, failedCount: 0, createdAt: '刚刚' }); }; return <div className="fixed inset-0 z-[90] flex items-center justify-center bg-black/35"><div className="w-[620px] rounded-lg bg-white shadow-2xl"><div className="flex h-14 items-center justify-between border-b border-[#E5E7EB] px-5"><div><h3 className="font-semibold">发起差异巡检</h3><p className="text-[12px] text-[#667085]">读取平台现状并与最近一次成功发布快照比较。</p></div><button onClick={onClose}><X size={20} className="text-[#667085]" /></button></div><div className="space-y-4 p-5 text-[13px]"><EditorField label="任务名称" required><input value={name} onChange={e => setName(e.target.value)} className="h-9 w-full rounded-md border border-[#DDE2E8] px-3" /></EditorField><EditorField label="巡检渠道" required><select value={channel} onChange={e => setChannel(e.target.value)} className="h-9 w-full rounded-md border border-[#DDE2E8] px-3"><option>美团外卖</option><option>饿了么</option><option>抖音团购</option></select></EditorField><EditorField label="门店范围" required><select value={stores} onChange={e => setStores(e.target.value)} className="h-9 w-full rounded-md border border-[#DDE2E8] px-3"><option>全部已绑定门店</option><option>指定区域门店</option><option>指定门店</option></select></EditorField><EditorField label="字段范围" required><select value={scope} onChange={e => setScope(e.target.value)} className="h-9 w-full rounded-md border border-[#DDE2E8] px-3"><option>全部字段</option><option>基础信息与图片</option><option>价格</option><option>分类与售卖状态</option></select></EditorField><div className="rounded-md bg-[#F7F8FA] p-3 text-[#667085]">预计读取：{channel} · {stores} · {scope}。巡检期间不锁定商品编辑和发布。</div>{error && <div className="ml-[112px] text-[#D92D20]">{error}</div>}</div><div className="flex justify-end gap-2 border-t border-[#E5E7EB] px-5 py-3"><button onClick={onClose} className="h-9 rounded-md border border-[#DDE2E8] px-4 text-[13px]">取消</button><button onClick={submit} className="h-9 rounded-md bg-[#00B460] px-4 text-[13px] font-medium text-white">开始巡检</button></div></div></div>; };

const ConfirmAction = ({ state, onClose, onConfirm }: { state: { action: 'overwrite' | 'accept' | 'ignore'; records: DifferenceRecord[] }; onClose: () => void; onConfirm: () => void }) => { const label = state.action === 'overwrite' ? '覆盖平台' : state.action === 'accept' ? '接受平台值' : '忽略差异'; return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/35"><div className="w-[480px] rounded-lg bg-white p-5 shadow-2xl"><div className="flex gap-3"><AlertTriangle size={22} className="shrink-0 text-[#F79009]" /><div><h3 className="font-semibold">确认{label}</h3><p className="mt-2 text-[13px] leading-6 text-[#667085]">共 {state.records.length} 条差异，涉及 {Array.from(new Set(state.records.map(item => item.channel))).join('、')}。</p><p className="text-[13px] leading-6 text-[#667085]">{state.action === 'overwrite' ? '将创建发布任务，预检通过后才会覆盖平台；失败可在发布中心重试。' : state.action === 'accept' ? '平台值将进入主档变更记录，按字段权限和协作策略审核后生效。' : '本次差异将关闭，后续巡检若仍不一致会再次发现。'}</p></div></div><div className="mt-5 flex justify-end gap-2"><button onClick={onClose} className="h-9 rounded-md border border-[#DDE2E8] px-4 text-[13px]">取消</button><button onClick={onConfirm} className="h-9 rounded-md bg-[#00B460] px-4 text-[13px] font-medium text-white">确认{label}</button></div></div></div>; };
const DrawerHeader = ({ title, onClose }: { title: string; onClose: () => void }) => <div className="flex h-14 shrink-0 items-center justify-between border-b border-[#E5E7EB] px-5"><h3 className="text-[17px] font-semibold">{title}</h3><button onClick={onClose}><X size={20} className="text-[#667085]" /></button></div>;
const Field = ({ label, value }: { label: string; value: string }) => <div><div className="text-[12px] text-[#98A2B3]">{label}</div><div className="mt-2 rounded-md border border-[#E5E7EB] p-3 leading-6">{value}</div></div>;
const EditorField = ({ label, required, children }: { label: string; required?: boolean; children: React.ReactNode }) => <div className="flex items-start"><div className="w-28 shrink-0 pt-2 text-right text-[#4E5969]">{required && <span className="mr-1 text-[#D92D20]">*</span>}{label}：</div><div className="min-w-0 flex-1 pl-4">{children}</div></div>;
const Select = ({ value, onChange, label, options, optionLabels }: { value: string; onChange: (value: string) => void; label: string; options: string[]; optionLabels?: Record<string, string> }) => <label className="relative"><select value={value} onChange={e => onChange(e.target.value)} className="h-9 w-40 appearance-none rounded-md border border-[#DDE2E8] bg-white px-3 pr-8 text-[13px]"><option value="all">{label}：全部</option>{options.map(item => <option key={item} value={item}>{optionLabels?.[item] || item}</option>)}</select><ChevronDown size={15} className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-[#98A2B3]" /></label>;
