import React, { useEffect, useMemo, useState } from 'react';
import { AlertCircle, ArrowLeft, ArrowRight, CheckCircle2, ChevronLeft, ChevronRight, Clock3, Loader2, Search, Store } from 'lucide-react';

type TaskType = 'update_platform_product' | 'auto_mapping';
type TaskStatus = 'completed' | 'running' | 'partial_failed' | 'failed';
type MappingResult = 'mapped' | 'failed' | 'unmapped';
type StoreResultStatus = 'success' | 'failed' | 'waiting';
type DetailView = 'stores' | 'products';
type MappingTask = { id: string; type: TaskType; createdAt: string; completedAt?: string; operator: string; status: TaskStatus; platform: string; storeCount: number; successCount: number; failedCount: number; waitingCount: number };
type StoreTaskResult = { store: string; storeCode: string; status: StoreResultStatus; processedCount: number; failedCount: number; completedAt?: string; issue?: string };
type ProductMappingDetail = { id: string; store: string; platformName: string; platformProductId: string; platformSku: string; platformSpec: string; qimaiName?: string; qimaiSku?: string; qimaiSpec?: string; result: MappingResult; reason?: string };

const initialTasks: MappingTask[] = [
  { id: '1297204877659642021', type: 'update_platform_product', createdAt: '2026-08-20 14:29:03', completedAt: '2026-08-20 14:29:31', operator: '孙猛', status: 'completed', platform: '美团外卖', storeCount: 1, successCount: 1, failedCount: 0, waitingCount: 0 },
  { id: '1291105153797521438', type: 'update_platform_product', createdAt: '2026-08-03 18:30:56', completedAt: '2026-08-03 18:31:27', operator: '刘剑', status: 'completed', platform: '美团外卖', storeCount: 1, successCount: 1, failedCount: 0, waitingCount: 0 },
  { id: '1291104345890684926', type: 'update_platform_product', createdAt: '2026-08-03 18:27:43', completedAt: '2026-08-03 18:28:21', operator: '刘剑', status: 'completed', platform: '淘宝闪购', storeCount: 1, successCount: 1, failedCount: 0, waitingCount: 0 },
  { id: '1291084481000043512', type: 'update_platform_product', createdAt: '2026-08-03 17:08:47', completedAt: '2026-08-03 17:09:42', operator: '刘剑', status: 'partial_failed', platform: '美团外卖', storeCount: 18, successCount: 16, failedCount: 2, waitingCount: 0 },
  { id: '1289688992479694210', type: 'auto_mapping', createdAt: '2026-07-30 20:43:20', completedAt: '2026-07-30 20:43:38', operator: '周镇', status: 'partial_failed', platform: '美团外卖', storeCount: 2734, successCount: 2730, failedCount: 4, waitingCount: 0 },
  { id: '1288564837265471496', type: 'update_platform_product', createdAt: '2026-07-27 18:16:37', operator: '刘剑', status: 'running', platform: '抖音在线点', storeCount: 42, successCount: 28, failedCount: 0, waitingCount: 14 },
  { id: '1288552271461963511', type: 'auto_mapping', createdAt: '2026-07-27 17:26:41', completedAt: '2026-07-27 17:27:12', operator: '刘剑', status: 'failed', platform: '美团外卖', storeCount: 3, successCount: 0, failedCount: 3, waitingCount: 0 },
];

const productMappingDetails: ProductMappingDetail[] = [
  { id: 'd1', store: '南山万象店', platformName: '招牌珍珠奶茶', platformProductId: '30824739921', platformSku: 'MT-1001-L', platformSpec: '大杯 / 冰', qimaiName: '招牌珍珠奶茶', qimaiSku: 'SKU 1001-02', qimaiSpec: '中杯 / 热 / 少糖', result: 'mapped' },
  { id: 'd2', store: '南山万象店', platformName: '手打柠檬茶', platformProductId: '30824739922', platformSku: 'MT-1002-N', platformSpec: '标准', qimaiName: '手打柠檬茶', qimaiSku: 'SKU 1002', qimaiSpec: '标准规格', result: 'mapped' },
  { id: 'd3', store: '福田卓悦店', platformName: '黑糖波波鲜奶', platformProductId: '30824739923', platformSku: 'MT-1003-M', platformSpec: '中杯', qimaiName: '黑糖波波鲜奶', qimaiSku: 'SKU 1003', qimaiSpec: '中杯', result: 'mapped' },
  { id: 'd4', store: '易到家（五一广场店）', platformName: '辣椒炒肉', platformProductId: '34581232438', platformSku: 'MT-2208-200', platformSpec: '200 克', qimaiName: '番茄水果茶', qimaiSku: 'SKU 1003', qimaiSpec: '大杯', result: 'failed', reason: '该门店商品已被其他平台商品绑定' },
  { id: 'd5', store: '宝安壹方城店', platformName: '经典牛肉汉堡', platformProductId: '30824739925', platformSku: 'MT-3001-N', platformSpec: '标准', result: 'unmapped', reason: '未找到可绑定的门店商品' },
  { id: 'd6', store: '龙岗万科店', platformName: '多肉葡萄', platformProductId: '30824739924', platformSku: 'MT-2002-L', platformSpec: '大杯', qimaiName: '多肉葡萄', qimaiSku: 'SKU 1004-01', qimaiSpec: '大杯', result: 'mapped' },
];

const taskTypeLabels: Record<TaskType, string> = { update_platform_product: '更新平台商品', auto_mapping: '自动关联' };
const statusMeta: Record<TaskStatus, { label: string; classes: string }> = {
  completed: { label: '已完成', classes: 'bg-[#E8FFF3] text-[#008A4B]' }, running: { label: '执行中', classes: 'bg-[#E8F3FF] text-[#2468A2]' },
  partial_failed: { label: '部分失败', classes: 'bg-[#FFF7E8] text-[#D46B08]' }, failed: { label: '失败', classes: 'bg-[#FFECE8] text-[#CB2634]' },
};
const resultMeta: Record<MappingResult, { label: string; classes: string }> = {
  mapped: { label: '已绑定', classes: 'bg-[#E8FFF3] text-[#008A4B]' }, failed: { label: '绑定失败', classes: 'bg-[#FFECE8] text-[#CB2634]' }, unmapped: { label: '未找到', classes: 'bg-[#FFF7E8] text-[#D46B08]' },
};
const storeStatusMeta: Record<StoreResultStatus, { label: string; classes: string }> = {
  success: { label: '成功', classes: 'bg-[#E8FFF3] text-[#008A4B]' }, failed: { label: '失败', classes: 'bg-[#FFECE8] text-[#CB2634]' }, waiting: { label: '等待执行', classes: 'bg-[#E8F3FF] text-[#2468A2]' },
};
const storeSamples = [
  ['南山万象店', 'STORE-10001'], ['福田卓悦店', 'STORE-10002'], ['龙岗万科店', 'STORE-10003'],
  ['宝安壹方城店', 'STORE-10004'], ['易到家（五一广场店）', 'STORE-10005'], ['罗湖万象城店', 'STORE-10006'],
];

const buildStoreResults = (task: MappingTask): StoreTaskResult[] => storeSamples.slice(0, Math.min(task.storeCount, storeSamples.length)).map(([store, storeCode], index, list) => {
  const failedVisible = Math.min(task.failedCount, list.length);
  const waitingVisible = Math.min(task.waitingCount, list.length - failedVisible);
  if (failedVisible && index >= list.length - failedVisible) return { store, storeCode, status: 'failed', processedCount: 23 + index, failedCount: index % 2 ? 2 : 1, completedAt: task.completedAt, issue: index % 2 ? '部分平台商品未找到可绑定的门店商品' : '存在已被其他平台商品占用的绑定关系' };
  if (waitingVisible && index >= list.length - failedVisible - waitingVisible) return { store, storeCode, status: 'waiting', processedCount: 0, failedCount: 0 };
  return { store, storeCode, status: 'success', processedCount: 28 + index * 3, failedCount: 0, completedAt: task.completedAt || '2026-07-27 18:17:02' };
});

const syncTaskUrl = (taskId?: string, detailView?: DetailView) => {
  const url = new URL(window.location.href);
  if (taskId) url.searchParams.set('task', taskId); else url.searchParams.delete('task');
  if (taskId && detailView) url.searchParams.set('detail', detailView); else url.searchParams.delete('detail');
  window.history.replaceState({}, '', `${url.pathname}${url.search}${url.hash}`);
};

const Pager: React.FC<{ total: number; suffix: string }> = ({ total, suffix }) => <div className="mt-3 flex items-center justify-end gap-2 text-[12px] text-[#667085]"><button type="button" disabled className="flex h-8 w-8 items-center justify-center rounded bg-[#F2F3F5] text-[#C9CDD4]" aria-label="上一页"><ChevronLeft size={15} /></button><span className="flex h-8 min-w-8 items-center justify-center rounded bg-[#00B460] px-2 font-bold text-white">1</span><button type="button" disabled className="flex h-8 w-8 items-center justify-center rounded bg-[#F2F3F5] text-[#C9CDD4]" aria-label="下一页"><ChevronRight size={15} /></button><span className="ml-1">共 {total} {suffix}</span></div>;

export const WebProductMappingTasks: React.FC = () => {
  const [taskIdInput, setTaskIdInput] = useState('');
  const [taskTypeInput, setTaskTypeInput] = useState<'all' | TaskType>('all');
  const [statusInput, setStatusInput] = useState<'all' | TaskStatus>('all');
  const [startDateInput, setStartDateInput] = useState('');
  const [endDateInput, setEndDateInput] = useState('');
  const [filters, setFilters] = useState({ taskId: '', taskType: 'all' as 'all' | TaskType, status: 'all' as 'all' | TaskStatus, startDate: '', endDate: '' });
  const [selectedTask, setSelectedTask] = useState<MappingTask | null>(() => initialTasks.find(task => task.id === new URLSearchParams(window.location.search).get('task')) || null);
  const [detailView, setDetailView] = useState<DetailView>(() => new URLSearchParams(window.location.search).get('detail') === 'products' ? 'products' : 'stores');
  const [detailStore, setDetailStore] = useState('all');
  const [detailKeyword, setDetailKeyword] = useState('');
  const [detailResult, setDetailResult] = useState<'all' | MappingResult>('all');
  const [storeKeyword, setStoreKeyword] = useState('');
  const [storeStatus, setStoreStatus] = useState<'all' | StoreResultStatus>('all');
  const [message, setMessage] = useState('');

  useEffect(() => { if (!message) return; const timer = window.setTimeout(() => setMessage(''), 2600); return () => window.clearTimeout(timer); }, [message]);
  const filteredTasks = useMemo(() => initialTasks.filter(task => {
    const date = task.createdAt.slice(0, 10);
    return (!filters.taskId || task.id.includes(filters.taskId)) && (filters.taskType === 'all' || task.type === filters.taskType) && (filters.status === 'all' || task.status === filters.status) && (!filters.startDate || date >= filters.startDate) && (!filters.endDate || date <= filters.endDate);
  }), [filters]);
  const storeResults = useMemo(() => selectedTask ? buildStoreResults(selectedTask) : [], [selectedTask]);
  const visibleStores = useMemo(() => storeResults.filter(result => (storeStatus === 'all' || result.status === storeStatus) && (!storeKeyword || `${result.store}${result.storeCode}${result.issue || ''}`.toLowerCase().includes(storeKeyword.toLowerCase()))), [storeKeyword, storeResults, storeStatus]);
  const visibleDetails = useMemo(() => productMappingDetails.filter(detail => (detailStore === 'all' || detail.store === detailStore) && (detailResult === 'all' || detail.result === detailResult) && (!detailKeyword || `${detail.platformName}${detail.platformProductId}${detail.platformSku}${detail.qimaiName || ''}${detail.qimaiSku || ''}`.toLowerCase().includes(detailKeyword.toLowerCase()))), [detailKeyword, detailResult, detailStore]);

  const query = () => setFilters({ taskId: taskIdInput.trim(), taskType: taskTypeInput, status: statusInput, startDate: startDateInput, endDate: endDateInput });
  const reset = () => { setTaskIdInput(''); setTaskTypeInput('all'); setStatusInput('all'); setStartDateInput(''); setEndDateInput(''); setFilters({ taskId: '', taskType: 'all', status: 'all', startDate: '', endDate: '' }); };
  const openTask = (task: MappingTask) => { setSelectedTask(task); setDetailView('stores'); setDetailStore('all'); setDetailKeyword(''); setDetailResult('all'); setStoreKeyword(''); setStoreStatus('all'); syncTaskUrl(task.id, 'stores'); };
  const closeTask = () => { setSelectedTask(null); syncTaskUrl(); };
  const switchDetailView = (view: DetailView) => { setDetailView(view); if (selectedTask) syncTaskUrl(selectedTask.id, view); };
  const retryTask = (task: MappingTask) => { closeTask(); setMessage(`已按任务 ${task.id} 的失败门店范围创建重试任务`); };

  if (selectedTask) return <div className="space-y-3">
    <section className="rounded-lg border border-[#E5E6EB] bg-white">
      <header className="flex min-h-[68px] items-center justify-between gap-4 border-b border-[#E5E6EB] px-5 py-3">
        <div className="flex min-w-0 items-center gap-3"><button type="button" onClick={closeTask} className="flex h-8 w-8 shrink-0 items-center justify-center rounded-md border border-[#C9CDD4] text-[#4E5969] hover:bg-[#F7F8FA]" aria-label="返回任务列表"><ArrowLeft size={16} /></button><div className="min-w-0"><div className="flex items-center gap-2"><h2 className="text-[16px] font-bold text-[#1D2129]">任务详情</h2><span className={`rounded px-2 py-0.5 text-[11px] font-medium ${statusMeta[selectedTask.status].classes}`}>{statusMeta[selectedTask.status].label}</span></div><div className="mt-1 truncate font-mono text-[11px] text-[#86909C]">任务 ID {selectedTask.id}</div></div></div>
        <div className="flex shrink-0 items-center gap-2"><button type="button" onClick={closeTask} className="h-9 whitespace-nowrap rounded-md border border-[#C9CDD4] bg-white px-4 text-[13px] text-[#4E5969]">返回任务列表</button>{selectedTask.failedCount > 0 && <button type="button" onClick={() => retryTask(selectedTask)} className="inline-flex h-9 items-center whitespace-nowrap rounded-md bg-[#00B460] px-4 text-[13px] font-bold text-white"><Loader2 size={14} className="mr-1.5" />重试失败范围</button>}</div>
      </header>
      <div className="grid divide-x divide-[#EEF0F3] border-b border-[#E5E6EB] bg-[#FAFBFC]" style={{ gridTemplateColumns: 'minmax(0, 1fr) 120px 120px 120px 120px' }}>
        <dl className="grid grid-cols-4 gap-x-5 gap-y-3 px-5 py-4 text-[12px]"><div><dt className="text-[#86909C]">操作类型</dt><dd className="mt-1 font-medium text-[#1D2129]">{taskTypeLabels[selectedTask.type]}</dd></div><div><dt className="text-[#86909C]">平台渠道</dt><dd className="mt-1 font-medium text-[#1D2129]">{selectedTask.platform}</dd></div><div><dt className="text-[#86909C]">创建时间</dt><dd className="mt-1 whitespace-nowrap tabular-nums text-[#1D2129]">{selectedTask.createdAt}</dd></div><div><dt className="text-[#86909C]">操作人</dt><dd className="mt-1 text-[#1D2129]">{selectedTask.operator}</dd></div><div className="col-span-2"><dt className="text-[#86909C]">完成时间</dt><dd className="mt-1 tabular-nums text-[#1D2129]">{selectedTask.completedAt || '--'}</dd></div><div className="col-span-2"><dt className="text-[#86909C]">执行范围</dt><dd className="mt-1 text-[#1D2129]">{selectedTask.storeCount} 家门店 · 免绑定商品已排除</dd></div></dl>
        {[['目标门店', selectedTask.storeCount, 'text-[#1D2129]'], ['成功', selectedTask.successCount, 'text-[#00A35B]'], ['失败', selectedTask.failedCount, 'text-[#CB2634]'], ['等待', selectedTask.waitingCount, 'text-[#2468A2]']].map(([label, value, color]) => <div key={label as string} className="px-4 py-5"><div className="text-[11px] text-[#86909C]">{label}</div><div className={`mt-2 text-[24px] font-bold tabular-nums ${color}`}>{value}</div></div>)}
      </div>
      <nav className="flex h-12 items-end gap-6 border-b border-[#E5E6EB] px-5" aria-label="任务详情视图"><button type="button" onClick={() => switchDetailView('stores')} className={`h-full border-b-2 px-1 text-[13px] ${detailView === 'stores' ? 'border-[#00B460] font-bold text-[#00A35B]' : 'border-transparent text-[#667085]'}`}>门店执行结果</button><button type="button" onClick={() => switchDetailView('products')} className={`h-full border-b-2 px-1 text-[13px] ${detailView === 'products' ? 'border-[#00B460] font-bold text-[#00A35B]' : 'border-transparent text-[#667085]'}`}>商品处理明细</button></nav>
      <div className="p-4">{detailView === 'stores' ? <>
        <div className="mb-3 flex items-center gap-2"><label className="flex h-9 min-w-[320px] max-w-[520px] flex-1 items-center rounded-md border border-[#C9CDD4] bg-white px-3"><Search size={15} className="mr-2 shrink-0 text-[#86909C]" /><input value={storeKeyword} onChange={event => setStoreKeyword(event.target.value)} placeholder="搜索门店名称或门店编号" className="min-w-0 flex-1 text-[12px] outline-none" /></label><select value={storeStatus} onChange={event => setStoreStatus(event.target.value as 'all' | StoreResultStatus)} className="h-9 w-[150px] rounded-md border border-[#C9CDD4] bg-white px-3 text-[12px]"><option value="all">全部执行结果</option><option value="success">成功</option><option value="failed">失败</option><option value="waiting">等待执行</option></select><span className="ml-auto text-[12px] text-[#86909C]">共 {selectedTask.storeCount} 家门店</span></div>
        <div className="overflow-x-auto rounded-md border border-[#E5E6EB]"><table className="w-full min-w-[980px] table-fixed text-left text-[12px]"><thead className="bg-[#F7F8FA] text-[#4E5969]"><tr><th className="w-[260px] px-4 py-3 font-medium">门店</th><th className="w-[120px] px-4 py-3 font-medium">执行结果</th><th className="w-[130px] px-4 py-3 font-medium">处理商品数</th><th className="w-[100px] px-4 py-3 font-medium">失败数</th><th className="px-4 py-3 font-medium">失败原因</th><th className="w-[160px] px-4 py-3 font-medium">完成时间</th><th className="w-[120px] px-4 py-3 font-medium">操作</th></tr></thead><tbody>{visibleStores.map(result => <tr key={result.storeCode} className="border-t border-[#F0F1F2] text-[#4E5969] hover:bg-[#FAFBFC]"><td className="px-4 py-3"><div className="flex items-center gap-2.5"><span className={`flex h-7 w-7 shrink-0 items-center justify-center rounded-full ${result.status === 'success' ? 'bg-[#E8FFF3] text-[#00A35B]' : result.status === 'waiting' ? 'bg-[#E8F3FF] text-[#2468A2]' : 'bg-[#FFECE8] text-[#CB2634]'}`}>{result.status === 'success' ? <CheckCircle2 size={15} /> : result.status === 'waiting' ? <Clock3 size={15} /> : <AlertCircle size={15} />}</span><div className="min-w-0"><div className="truncate font-medium text-[#1D2129]">{result.store}</div><div className="mt-1 font-mono text-[10px] text-[#86909C]">{result.storeCode}</div></div></div></td><td className="px-4 py-3"><span className={`inline-flex whitespace-nowrap rounded px-2 py-1 text-[11px] font-medium ${storeStatusMeta[result.status].classes}`}>{storeStatusMeta[result.status].label}</span></td><td className="px-4 py-3 tabular-nums">{result.status === 'waiting' ? '--' : result.processedCount}</td><td className={`px-4 py-3 tabular-nums ${result.failedCount ? 'font-semibold text-[#CB2634]' : 'text-[#86909C]'}`}>{result.status === 'waiting' ? '--' : result.failedCount}</td><td className="px-4 py-3"><span className={result.issue ? 'text-[#CB2634]' : 'text-[#86909C]'}>{result.issue || '--'}</span></td><td className="px-4 py-3 tabular-nums">{result.completedAt || '--'}</td><td className="px-4 py-3"><button type="button" onClick={() => { setDetailStore(result.store); switchDetailView('products'); }} className="inline-flex items-center whitespace-nowrap font-medium text-[#00A35B]">查看商品明细<ArrowRight size={13} className="ml-1" /></button></td></tr>)}</tbody></table>{visibleStores.length === 0 && <div className="py-14 text-center text-[12px] text-[#86909C]">没有符合当前条件的门店结果</div>}</div><Pager total={selectedTask.storeCount} suffix="家" />
      </> : <>
        <div className="mb-3 flex flex-nowrap items-center gap-2 overflow-x-auto pb-0.5"><label className="flex h-9 min-w-[320px] flex-1 items-center rounded-md border border-[#C9CDD4] bg-white px-3"><Search size={15} className="mr-2 shrink-0 text-[#86909C]" /><input value={detailKeyword} onChange={event => setDetailKeyword(event.target.value)} placeholder="搜索平台商品名称、商品 ID、SKU 码或企迈商品" className="min-w-0 flex-1 text-[12px] outline-none" /></label><select value={detailStore} onChange={event => setDetailStore(event.target.value)} className="h-9 w-[200px] shrink-0 rounded-md border border-[#C9CDD4] bg-white px-3 text-[12px]"><option value="all">全部门店</option>{Array.from(new Set(productMappingDetails.map(item => item.store))).map(store => <option key={store} value={store}>{store}</option>)}</select><select value={detailResult} onChange={event => setDetailResult(event.target.value as 'all' | MappingResult)} className="h-9 w-[140px] shrink-0 rounded-md border border-[#C9CDD4] bg-white px-3 text-[12px]"><option value="all">全部处理结果</option><option value="mapped">已绑定</option><option value="failed">绑定失败</option><option value="unmapped">未找到</option></select><button type="button" onClick={() => { setDetailKeyword(''); setDetailStore('all'); setDetailResult('all'); }} className="h-9 shrink-0 whitespace-nowrap rounded-md border border-[#C9CDD4] bg-white px-3 text-[12px] text-[#4E5969]">重置</button></div>
        <div className="overflow-x-auto rounded-md border border-[#E5E6EB]"><table className="w-full min-w-[1120px] table-fixed text-left text-[12px]"><thead className="bg-[#F7F8FA] text-[#4E5969]"><tr><th className="w-[210px] px-4 py-3 font-medium">门店</th><th className="w-[270px] px-4 py-3 font-medium">平台商品 / 规格</th><th className="w-[200px] px-4 py-3 font-medium">平台商品标识</th><th className="w-[270px] px-4 py-3 font-medium">绑定的企迈商品 / SKU</th><th className="px-4 py-3 font-medium">处理结果 / 原因</th></tr></thead><tbody>{visibleDetails.map(detail => <tr key={detail.id} className="border-t border-[#F0F1F2] text-[#4E5969] hover:bg-[#FAFBFC]"><td className="px-4 py-3"><div className="flex min-w-0 items-center gap-2"><Store size={14} className="shrink-0 text-[#86909C]" /><span className="truncate font-medium text-[#1D2129]">{detail.store}</span></div></td><td className="px-4 py-3"><div className="truncate font-medium text-[#1D2129]">{detail.platformName}</div><div className="mt-1 truncate text-[11px] text-[#86909C]">{detail.platformSpec}</div></td><td className="px-4 py-3"><div className="truncate font-mono text-[11px]">商品 ID {detail.platformProductId}</div><div className="mt-1 truncate font-mono text-[11px] text-[#86909C]">SKU 码 {detail.platformSku}</div></td><td className="px-4 py-3">{detail.qimaiName ? <><div className="truncate font-medium text-[#1D2129]">{detail.qimaiName}</div><div className="mt-1 truncate text-[11px] text-[#86909C]">{detail.qimaiSpec} · {detail.qimaiSku}</div></> : <span className="text-[#86909C]">未绑定企迈商品</span>}</td><td className="px-4 py-3"><span className={`inline-flex whitespace-nowrap rounded px-2 py-1 text-[11px] font-medium ${resultMeta[detail.result].classes}`}>{resultMeta[detail.result].label}</span>{detail.reason && <div className="mt-1.5 text-[11px] leading-4 text-[#CB2634]">{detail.reason}</div>}</td></tr>)}</tbody></table>{visibleDetails.length === 0 && <div className="py-14 text-center text-[12px] text-[#86909C]">没有符合当前条件的商品处理明细</div>}</div>
      </>}</div>
    </section>
  </div>;

  return <div className="space-y-3">
    {message && <div role="status" aria-live="polite" className="fixed right-6 top-[68px] z-[500] flex max-w-[440px] items-start gap-2.5 rounded-lg border border-[#BFEBD3] bg-white px-4 py-3 text-[13px] leading-5 text-[#1D2129] shadow-[0_8px_28px_rgba(29,33,41,0.16)]"><span className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-[#00B460] text-white"><CheckCircle2 size={13} /></span><span>{message}</span></div>}
    <section className="rounded-lg border border-[#E5E6EB] bg-white p-4"><div className="grid grid-cols-[minmax(340px,1.35fr)_minmax(220px,1fr)_minmax(180px,.8fr)] gap-3">
      <label><span className="mb-1.5 block text-[12px] font-medium text-[#4E5969]">创建时间</span><div className="grid grid-cols-[1fr_auto_1fr] items-center gap-2"><input type="date" value={startDateInput} onChange={event => setStartDateInput(event.target.value)} className="h-9 min-w-0 rounded-md border border-[#C9CDD4] px-3 text-[13px] outline-none focus:border-[#00B460]" /><span className="text-[12px] text-[#86909C]">至</span><input type="date" value={endDateInput} onChange={event => setEndDateInput(event.target.value)} className="h-9 min-w-0 rounded-md border border-[#C9CDD4] px-3 text-[13px] outline-none focus:border-[#00B460]" /></div></label>
      <label><span className="mb-1.5 block text-[12px] font-medium text-[#4E5969]">任务 ID</span><div className="flex h-9 items-center rounded-md border border-[#C9CDD4] bg-white px-3"><Search size={15} className="mr-2 shrink-0 text-[#86909C]" /><input value={taskIdInput} onChange={event => setTaskIdInput(event.target.value)} onKeyDown={event => { if (event.key === 'Enter') query(); }} placeholder="请输入任务 ID" className="min-w-0 flex-1 text-[13px] outline-none" /></div></label>
      <label><span className="mb-1.5 block text-[12px] font-medium text-[#4E5969]">操作类型</span><select value={taskTypeInput} onChange={event => setTaskTypeInput(event.target.value as 'all' | TaskType)} className="h-9 w-full rounded-md border border-[#C9CDD4] bg-white px-3 text-[13px]"><option value="all">全部操作类型</option><option value="update_platform_product">更新平台商品</option><option value="auto_mapping">自动关联</option></select></label>
      <label><span className="mb-1.5 block text-[12px] font-medium text-[#4E5969]">执行状态</span><select value={statusInput} onChange={event => setStatusInput(event.target.value as 'all' | TaskStatus)} className="h-9 w-full rounded-md border border-[#C9CDD4] bg-white px-3 text-[13px]"><option value="all">全部状态</option><option value="completed">已完成</option><option value="running">执行中</option><option value="partial_failed">部分失败</option><option value="failed">失败</option></select></label>
      <div className="col-span-2 flex items-end gap-2"><button type="button" onClick={query} className="h-9 shrink-0 whitespace-nowrap rounded-md bg-[#00B460] px-5 text-[13px] font-bold text-white">查询</button><button type="button" onClick={reset} className="h-9 shrink-0 whitespace-nowrap rounded-md border border-[#C9CDD4] bg-white px-5 text-[13px]">重置</button></div>
    </div></section>
    <section className="overflow-hidden rounded-lg border border-[#E5E6EB] bg-white"><div className="flex min-h-11 items-center justify-between gap-4 border-b border-[#E5E6EB] px-4 py-2 text-[12px] text-[#86909C]"><span>共 {filteredTasks.length} 条任务</span><span>免绑定商品在任务创建前排除，本页仅统计实际进入执行范围的商品</span></div><div className="overflow-x-auto"><table className="w-full min-w-[1040px] table-fixed text-left text-[13px]"><thead className="bg-[#F7F8FA] text-[#4E5969]"><tr><th className="w-[188px] px-4 py-3 font-medium">任务 ID</th><th className="w-[132px] px-4 py-3 font-medium">操作类型</th><th className="w-[164px] px-4 py-3 font-medium">创建时间</th><th className="w-[72px] px-4 py-3 font-medium">操作人</th><th className="w-[130px] px-4 py-3 font-medium">执行状态</th><th className="w-[90px] px-4 py-3 font-medium">门店数</th><th className="w-[190px] px-4 py-3 font-medium">执行结果</th><th className="w-[90px] px-4 py-3 font-medium">操作</th></tr></thead><tbody>
      {filteredTasks.map(task => <tr key={task.id} className="border-t border-[#F0F1F2] text-[#4E5969] hover:bg-[#FAFBFC]"><td className="px-4 py-3 font-mono text-[12px] text-[#1D2129]">{task.id}</td><td className="px-4 py-3"><div className="font-medium text-[#1D2129]">{taskTypeLabels[task.type]}</div><div className="mt-1 text-[11px] text-[#86909C]">{task.platform}</div></td><td className="px-4 py-3 tabular-nums">{task.createdAt}</td><td className="px-4 py-3">{task.operator}</td><td className="px-4 py-3"><span className={`inline-flex whitespace-nowrap rounded px-2 py-1 text-[12px] font-medium ${statusMeta[task.status].classes}`}>{statusMeta[task.status].label}</span>{task.completedAt && <div className="mt-1 whitespace-nowrap text-[11px] text-[#86909C]">{task.completedAt.slice(5)}</div>}</td><td className="px-4 py-3 font-medium tabular-nums text-[#1D2129]">{task.storeCount}</td><td className="px-4 py-3"><div className="flex flex-nowrap gap-1.5"><span className="whitespace-nowrap rounded bg-[#E8FFF3] px-2 py-1 text-[11px] text-[#008A4B]">成功 {task.successCount}</span><span className={`whitespace-nowrap rounded px-2 py-1 text-[11px] ${task.failedCount ? 'bg-[#FFECE8] font-semibold text-[#CB2634]' : 'bg-[#F2F3F5] text-[#86909C]'}`}>失败 {task.failedCount}</span>{task.waitingCount > 0 && <span className="whitespace-nowrap rounded bg-[#E8F3FF] px-2 py-1 text-[11px] text-[#2468A2]">等待 {task.waitingCount}</span>}</div></td><td className="px-4 py-3"><button type="button" onClick={() => openTask(task)} className="whitespace-nowrap font-medium text-[#00A35B]">查看详情</button></td></tr>)}
      {filteredTasks.length === 0 && <tr><td colSpan={8} className="px-4 py-16 text-center text-[13px] text-[#86909C]">没有符合当前条件的任务</td></tr>}
    </tbody></table></div><footer className="px-4 pb-3"><Pager total={filteredTasks.length} suffix="条" /></footer></section>
  </div>;
};
