import React, { useMemo, useState } from 'react';
import { AlertTriangle, ChevronDown, MoreHorizontal, Plus, Search, X } from 'lucide-react';

export type RequiredPolicyRecord = { id: string; name: string; targetName: string; targetType: '商品分类' | '商品'; stores: string[]; updatedAt: string };

export const MOCK_REQUIRED_POLICIES: RequiredPolicyRecord[] = [
  { id: 'policy-1', name: '测试11', targetName: '方案商品111', targetType: '商品分类', stores: ['范先生的门店', '南山万象店'], updatedAt: '2026-05-10 09:20' },
  { id: 'policy-2', name: '111', targetName: '新时测测试', targetType: '商品分类', stores: ['福田卓悦店'], updatedAt: '2026-05-09 18:32' },
  { id: 'policy-3', name: 'hulh必选方案11', targetName: '热销菜1003, 热销菜1002, 热销菜1001', targetType: '商品', stores: ['南山万象店', '福田卓悦店', '宝安壹方城店'], updatedAt: '2026-05-08 16:11' },
  { id: 'policy-4', name: '测试', targetName: '霸王西瓜汁', targetType: '商品', stores: ['范先生的门店'], updatedAt: '2026-05-07 14:45' },
  { id: 'policy-5', name: '测试必选', targetName: '标准商品', targetType: '商品分类', stores: ['南山万象店', '龙华红山店'], updatedAt: '2026-05-06 10:08' },
];

export const WebRequiredProductPolicyList: React.FC<{ onCreatePolicy?: () => void; onEditPolicy?: (policy: RequiredPolicyRecord) => void }> = ({ onCreatePolicy, onEditPolicy }) => {
  const [policies, setPolicies] = useState(MOCK_REQUIRED_POLICIES);
  const [keyword, setKeyword] = useState('');
  const [targetType, setTargetType] = useState<'all' | RequiredPolicyRecord['targetType']>('all');
  const [storeKeyword, setStoreKeyword] = useState('');
  const [detail, setDetail] = useState<RequiredPolicyRecord | null>(null);
  const [deletePolicy, setDeletePolicy] = useState<RequiredPolicyRecord | null>(null);
  const [exceptionOpen, setExceptionOpen] = useState(false);
  const [moreId, setMoreId] = useState<string | null>(null);
  const [toast, setToast] = useState('');
  const filteredPolicies = useMemo(() => policies.filter(item => {
    const query = keyword.trim().toLowerCase();
    if (query && ![item.name, item.targetName, item.id].join(' ').toLowerCase().includes(query)) return false;
    if (targetType !== 'all' && item.targetType !== targetType) return false;
    return !storeKeyword.trim() || item.stores.join(' ').toLowerCase().includes(storeKeyword.trim().toLowerCase());
  }), [keyword, policies, storeKeyword, targetType]);
  const reset = () => { setKeyword(''); setTargetType('all'); setStoreKeyword(''); };
  const feedback = (text: string) => { setToast(text); window.setTimeout(() => setToast(''), 2400); };

  return <div className="relative flex min-h-0 min-w-0 flex-1 overflow-hidden bg-[#F5F6FA] p-3">
    {toast && <div className="absolute left-1/2 top-4 z-[100] -translate-x-1/2 rounded-md bg-[#1D2129] px-4 py-2 text-[13px] text-white shadow-lg">{toast}</div>}
    <div className="console-panel flex min-h-0 min-w-0 flex-1 flex-col overflow-hidden">
      <div className="flex shrink-0 items-center justify-between gap-3 border-b border-[#E9EDF2] px-4 py-3"><div className="flex min-w-0 items-center gap-2"><label className="relative"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-[#98A2B3]" /><input value={keyword} onChange={e => setKeyword(e.target.value)} placeholder="方案名称、商品/分类、方案ID" className="h-9 w-[280px] rounded-md border border-[#DDE2E8] pl-9 pr-3 text-[13px] outline-none focus:border-[#00B460]" /></label><label className="relative"><select value={targetType} onChange={e => setTargetType(e.target.value as typeof targetType)} className="h-9 w-40 appearance-none rounded-md border border-[#DDE2E8] bg-white px-3 pr-8 text-[13px]"><option value="all">必选对象：全部</option><option value="商品">商品</option><option value="商品分类">商品分类</option></select><ChevronDown size={15} className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-[#98A2B3]" /></label><input value={storeKeyword} onChange={e => setStoreKeyword(e.target.value)} placeholder="适用门店" className="h-9 w-44 rounded-md border border-[#DDE2E8] px-3 text-[13px] outline-none" /><button onClick={reset} className="h-9 rounded-md border border-[#DDE2E8] px-4 text-[13px]">重置</button></div><div className="flex shrink-0 gap-2"><button onClick={() => setExceptionOpen(true)} className="h-9 rounded-md border border-[#DDE2E8] px-4 text-[13px] text-[#4E5969]">特例设置</button><button onClick={onCreatePolicy} className="inline-flex h-9 items-center rounded-md bg-[#00B460] px-4 text-[13px] font-medium text-white"><Plus size={15} className="mr-1.5" />新增必选商品</button></div></div>
      <div className="flex shrink-0 items-center justify-between border-b border-[#E9EDF2] px-4 py-2.5 text-[13px] text-[#667085]"><span>共 <strong className="text-[#1D2129]">{filteredPolicies.length}</strong> 个方案 · 商品方案 {policies.filter(item => item.targetType === '商品').length} 个 · 分类方案 {policies.filter(item => item.targetType === '商品分类').length} 个</span><span>同一门店命中多个方案时，点单需同时满足</span></div>
      <div className="min-h-0 flex-1 overflow-auto"><table className="w-full min-w-[1040px] table-fixed border-collapse text-left text-[13px]"><thead className="sticky top-0 z-10 bg-[#F7F8FA] text-[#4E5969]"><tr className="border-b border-[#E5E7EB]"><th className="w-[220px] px-4 py-3 font-medium">方案名称 / ID</th><th className="px-3 py-3 font-medium">商品 / 分类名称</th><th className="w-[260px] px-3 py-3 font-medium">适用门店</th><th className="w-[160px] px-3 py-3 font-medium">更新时间</th><th className="w-[160px] px-3 py-3 font-medium">操作</th></tr></thead><tbody>{filteredPolicies.map(policy => <tr key={policy.id} className="border-b border-[#EEF0F3] hover:bg-[#FAFCFB]"><td className="px-4 py-3"><button onClick={() => setDetail(policy)} className="font-medium text-[#1D2129] hover:text-[#008F4C]">{policy.name}</button><div className="mt-1 text-[12px] text-[#98A2B3]">ID：{policy.id}</div></td><td className="px-3 py-3"><div className="line-clamp-2 text-[#344054]">{policy.targetName}</div><span className="mt-1 inline-block rounded bg-[#EEF8F3] px-1.5 py-0.5 text-[12px] text-[#008F4C]">{policy.targetType}</span></td><td className="px-3 py-3"><div className="truncate">{policy.stores.slice(0, 2).join('、')}</div>{policy.stores.length > 2 && <div className="mt-1 text-[12px] text-[#008F4C]">另 {policy.stores.length - 2} 家</div>}</td><td className="px-3 py-3 text-[#667085]">{policy.updatedAt}</td><td className="px-3 py-3"><div className="relative flex gap-3"><button onClick={() => setDetail(policy)} className="text-[#008F4C]">查看</button><button onClick={() => onEditPolicy?.(policy)} className="text-[#008F4C]">编辑</button><button onClick={() => setMoreId(moreId === policy.id ? null : policy.id)}><MoreHorizontal size={17} className="text-[#667085]" /></button>{moreId === policy.id && <div className="absolute right-0 top-7 z-30 w-28 rounded-md border border-[#E5E7EB] bg-white py-1 shadow-lg"><button onClick={() => { setPolicies(current => [{ ...policy, id: `policy-${Date.now()}`, name: `${policy.name}-副本`, updatedAt: '刚刚' }, ...current]); setMoreId(null); feedback('必选方案已复制'); }} className="w-full px-3 py-2 text-left hover:bg-[#F7F8FA]">复制</button><button onClick={() => { setDeletePolicy(policy); setMoreId(null); }} className="w-full px-3 py-2 text-left text-[#D92D20] hover:bg-[#FFF5F5]">删除</button></div>}</div></td></tr>)}</tbody></table>{filteredPolicies.length === 0 && <div className="flex h-56 flex-col items-center justify-center text-[13px] text-[#98A2B3]"><Search size={28} className="mb-3" /><span>没有符合当前条件的必选商品方案</span><button onClick={reset} className="mt-2 text-[#008F4C]">清空筛选</button></div>}</div>
    </div>
    {detail && <div className="fixed inset-0 z-[80] flex justify-end bg-black/35"><div className="flex h-full w-[540px] flex-col bg-white shadow-2xl"><div className="flex h-14 items-center justify-between border-b border-[#E5E7EB] px-5"><h3 className="text-[17px] font-semibold">必选方案详情</h3><button onClick={() => setDetail(null)}><X size={20} className="text-[#667085]" /></button></div><div className="flex-1 space-y-5 overflow-y-auto p-5 text-[13px]"><div className="rounded-md bg-[#F7F8FA] p-4"><div className="font-medium">{detail.name}</div><div className="mt-1 text-[#667085]">ID：{detail.id} · 更新于 {detail.updatedAt}</div></div><DetailField label="必选对象" value={`${detail.targetType} · ${detail.targetName}`} /><DetailField label="适用门店" value={detail.stores.join('、')} /><DetailField label="点单约束" value="命中该方案的堂食/外卖订单需满足编辑页配置的必选数量后方可提交。" /></div><div className="flex justify-end gap-2 border-t border-[#E5E7EB] px-5 py-3"><button onClick={() => setDetail(null)} className="h-9 rounded-md border border-[#DDE2E8] px-4 text-[13px]">关闭</button><button onClick={() => { setDetail(null); onEditPolicy?.(detail); }} className="h-9 rounded-md bg-[#00B460] px-4 text-[13px] font-medium text-white">编辑方案</button></div></div></div>}
    {exceptionOpen && <div className="fixed inset-0 z-[80] flex items-center justify-center bg-black/35"><div className="w-[620px] rounded-lg bg-white shadow-2xl"><div className="flex h-14 items-center justify-between border-b border-[#E5E7EB] px-5"><div><h3 className="font-semibold">特例设置</h3><p className="text-[12px] text-[#667085]">为指定门店临时豁免已命中的必选方案。</p></div><button onClick={() => setExceptionOpen(false)}><X size={20} className="text-[#667085]" /></button></div><div className="space-y-4 p-5 text-[13px]"><label className="block"><span className="mb-2 block text-[#4E5969]">必选方案</span><select className="h-9 w-full rounded-md border border-[#DDE2E8] px-3"><option>请选择必选方案</option>{policies.map(item => <option key={item.id}>{item.name}</option>)}</select></label><label className="block"><span className="mb-2 block text-[#4E5969]">豁免门店</span><input placeholder="搜索并选择门店" className="h-9 w-full rounded-md border border-[#DDE2E8] px-3" /></label><label className="block"><span className="mb-2 block text-[#4E5969]">豁免原因</span><textarea rows={3} placeholder="请输入原因，便于审计" className="w-full resize-none rounded-md border border-[#DDE2E8] px-3 py-2" /></label></div><div className="flex justify-end gap-2 border-t border-[#E5E7EB] px-5 py-3"><button onClick={() => setExceptionOpen(false)} className="h-9 rounded-md border border-[#DDE2E8] px-4 text-[13px]">取消</button><button onClick={() => { setExceptionOpen(false); feedback('特例已保存，后续点单校验将按新范围生效'); }} className="h-9 rounded-md bg-[#00B460] px-4 text-[13px] font-medium text-white">保存特例</button></div></div></div>}
    {deletePolicy && <div className="fixed inset-0 z-[90] flex items-center justify-center bg-black/35"><div className="w-[460px] rounded-lg bg-white p-5 shadow-2xl"><div className="flex gap-3"><AlertTriangle size={22} className="shrink-0 text-[#F79009]" /><div><h3 className="font-semibold">删除必选商品方案</h3><p className="mt-2 text-[13px] leading-6 text-[#667085]">方案“{deletePolicy.name}”当前适用于 {deletePolicy.stores.length} 家门店。删除后新订单不再执行该必选约束，历史订单不受影响，操作不可恢复。</p></div></div><div className="mt-5 flex justify-end gap-2"><button onClick={() => setDeletePolicy(null)} className="h-9 rounded-md border border-[#DDE2E8] px-4 text-[13px]">取消</button><button onClick={() => { setPolicies(current => current.filter(item => item.id !== deletePolicy.id)); feedback(`方案“${deletePolicy.name}”已删除`); setDeletePolicy(null); }} className="h-9 rounded-md bg-[#D92D20] px-4 text-[13px] font-medium text-white">确认删除</button></div></div></div>}
  </div>;
};

const DetailField = ({ label, value }: { label: string; value: string }) => <div><div className="text-[12px] text-[#98A2B3]">{label}</div><div className="mt-2 rounded-md border border-[#E5E7EB] p-3 leading-6 text-[#344054]">{value}</div></div>;
