import React, { useMemo, useState } from 'react';
import { ArrowDown, ArrowUp, ArrowUpDown, ChevronDown, Search } from 'lucide-react';

type StoreOption = { id: string; name: string };
export type StoreRegionRecord = { id: string; storeId: string; sort: number; name: string; relatedProductCount: number };
const STORE_OPTIONS: StoreOption[] = [{ id: 'all', name: '全部门店' }, { id: 's1', name: '范先生的门店' }, { id: 's2', name: '南山万象店' }, { id: 's3', name: '福田卓悦店' }];
export const MOCK_STORE_REGIONS: StoreRegionRecord[] = [
  { id: 'region-1', storeId: 's1', sort: 1, name: '1楼', relatedProductCount: 0 }, { id: 'region-2', storeId: 's1', sort: 2, name: '2楼', relatedProductCount: 0 }, { id: 'region-3', storeId: 's2', sort: 1, name: 'A区', relatedProductCount: 12 }, { id: 'region-4', storeId: 's3', sort: 1, name: '外摆区', relatedProductCount: 6 },
];

export const WebStoreRegionList: React.FC<{ onEditRegion?: (region: StoreRegionRecord) => void }> = ({ onEditRegion }) => {
  const [regions, setRegions] = useState(MOCK_STORE_REGIONS);
  const [storeId, setStoreId] = useState('s1');
  const [keyword, setKeyword] = useState('');
  const [sorting, setSorting] = useState(false);
  const [toast, setToast] = useState('');
  const filteredRegions = useMemo(() => regions.filter(item => (storeId === 'all' || item.storeId === storeId) && (!keyword.trim() || item.name.includes(keyword.trim()))).sort((a, b) => a.sort - b.sort), [keyword, regions, storeId]);
  const move = (region: StoreRegionRecord, direction: -1 | 1) => { const siblings = regions.filter(item => item.storeId === region.storeId).sort((a, b) => a.sort - b.sort); const index = siblings.findIndex(item => item.id === region.id); const target = siblings[index + direction]; if (!target) return; setRegions(current => current.map(item => item.id === region.id ? { ...item, sort: target.sort } : item.id === target.id ? { ...item, sort: region.sort } : item)); };
  return <div className="relative flex min-h-0 min-w-0 flex-1 overflow-hidden bg-[#F5F6FA] p-3">{toast && <div className="absolute left-1/2 top-4 z-50 -translate-x-1/2 rounded-md bg-[#1D2129] px-4 py-2 text-[13px] text-white">{toast}</div>}<div className="console-panel flex min-h-0 min-w-0 flex-1 flex-col overflow-hidden">
    <div className="flex shrink-0 items-center justify-between gap-3 border-b border-[#E9EDF2] px-4 py-3"><div className="flex items-center gap-2"><label className="relative"><select value={storeId} onChange={e => setStoreId(e.target.value)} className="h-9 w-[240px] appearance-none rounded-md border border-[#DDE2E8] bg-white px-3 pr-8 text-[13px]">{STORE_OPTIONS.map(option => <option key={option.id} value={option.id}>{option.name}</option>)}</select><ChevronDown size={15} className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-[#98A2B3]" /></label><label className="relative"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-[#98A2B3]" /><input value={keyword} onChange={e => setKeyword(e.target.value)} placeholder="区域名称" className="h-9 w-48 rounded-md border border-[#DDE2E8] pl-9 pr-3 text-[13px]" /></label><button onClick={() => { setStoreId('s1'); setKeyword(''); }} className="h-9 rounded-md border border-[#DDE2E8] px-4 text-[13px]">重置</button></div><div className="flex gap-2">{sorting && <button onClick={() => { setSorting(false); setToast('区域排序已保存，仅影响堂食桌点单页展示顺序'); window.setTimeout(() => setToast(''), 2400); }} className="h-9 rounded-md border border-[#DDE2E8] px-4 text-[13px]">完成排序</button>}<button onClick={() => setSorting(value => !value)} className="inline-flex h-9 items-center rounded-md bg-[#00B460] px-4 text-[13px] font-medium text-white"><ArrowUpDown size={14} className="mr-1.5" />{sorting ? '退出排序' : '排序管理'}</button></div></div>
    <div className="flex shrink-0 items-center justify-between border-b border-[#E9EDF2] px-4 py-2.5 text-[13px] text-[#667085]"><span>共 <strong className="text-[#1D2129]">{filteredRegions.length}</strong> 个区域 · 已关联商品 {filteredRegions.reduce((sum, item) => sum + item.relatedProductCount, 0)} 个</span><span>区域来源于机构门店设置；本页只维护堂食桌点单页排序和关联商品</span></div>
    <div className="min-h-0 flex-1 overflow-auto"><table className="w-full min-w-[780px] table-fixed border-collapse text-left text-[13px]"><thead className="sticky top-0 z-10 bg-[#F7F8FA] text-[#4E5969]"><tr className="border-b border-[#E5E7EB]"><th className="w-[130px] px-4 py-3 font-medium">排序</th><th className="px-3 py-3 font-medium">区域名称</th><th className="w-[220px] px-3 py-3 font-medium">所属门店</th><th className="w-[160px] px-3 py-3 font-medium">关联商品</th><th className="w-[120px] px-3 py-3 font-medium">操作</th></tr></thead><tbody>{filteredRegions.map(region => <tr key={region.id} className="border-b border-[#EEF0F3] hover:bg-[#FAFCFB]"><td className="px-4 py-3">{sorting ? <div className="flex items-center gap-2"><button onClick={() => move(region, -1)} className="rounded border border-[#DDE2E8] p-1"><ArrowUp size={14} /></button><span className="w-6 text-center">{region.sort}</span><button onClick={() => move(region, 1)} className="rounded border border-[#DDE2E8] p-1"><ArrowDown size={14} /></button></div> : region.sort}</td><td className="px-3 py-3 font-medium">{region.name}</td><td className="px-3 py-3">{STORE_OPTIONS.find(item => item.id === region.storeId)?.name || region.storeId}</td><td className="px-3 py-3">{region.relatedProductCount} 个</td><td className="px-3 py-3"><button onClick={() => onEditRegion?.(region)} className="text-[#008F4C]">管理商品</button></td></tr>)}</tbody></table>{filteredRegions.length === 0 && <div className="flex h-56 flex-col items-center justify-center text-[13px] text-[#98A2B3]"><Search size={28} className="mb-3" /><span>没有符合当前条件的门店区域</span><button onClick={() => { setStoreId('all'); setKeyword(''); }} className="mt-2 text-[#008F4C]">清空筛选</button></div>}</div>
  </div></div>;
};
